#all local environment
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    publisher-confirm-type: correlated
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#debug: true
file-storage-directory: "D:/00data/file-storage"
springdoc:
  show-actuator: true
  #  use-management-port: true
  packagesToScan: com.boo.controller
