spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456
  redis:
    host: 39.105.6.92
    port: 6379
    password: "*#06#"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl